FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/participacao_eleitoral/dashboard.py .

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py", "--server.headless", "true", "--server.port", "8501"]