FROM apache/airflow:2.9.0-python3.11

USER airflow

COPY airflow/dags /opt/airflow/dags

ENV AIRFLOW__CORE__EXECUTOR=None
ENV AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
ENV AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080

EXPOSE 8080

CMD ["airflow", "webserver"]